#include "PatternsConsole/PlayWithDucks.h"
#include "PatternsLib/Facade/Amplifier.h"
#include "PatternsLib/Facade/CdPlayer.h"
#include "PatternsLib/Facade/DvdPlayer.h"
#include "PatternsLib/Facade/Screen.h"
#include "PatternsLib/Facade/PopcornPopper.h"
#include "PatternsLib/Facade/Tuner.h"
#include "PatternsLib/Facade/TheaterLights.h"
#include "PatternsLib/Facade/Projector.h"


namespace Patterns {
  void playWithHomeTheater() {

    // Create all the parts of the home theatre system
    auto amp = std::make_shared<Amplifier>("Yamaha RX-V377 Amplifier");
    auto cd = std::make_shared<CdPlayer>("Marantz A8005 CD Player", amp);
    auto dvd = std::make_shared<DvdPlayer>("My Dvd player", amp);
    auto screen = std::make_shared<Screen>("My Screen");
    auto popper = std::make_shared<PopcornPopper>("My Popcorn Popper");
    auto tuner = std::make_shared<Tuner>("My Tuner", amp);
    auto lights = std::make_shared<TheaterLights>("My Lights");
    auto projector = std::make_shared<Projector>("My Projector");

    popper->on();  // Turn on the popcorn popper...
    popper->pop(); // and start popping...

    lights->dim(10); // Dim the lights to 10%... 
    
    screen->down();  // Put the screen down...

    projector->on();             // Turn on the projector...
    projector->setInput(dvd);    // set it to DVD...
    projector->wideScreenMode(); // and put it on wide screen mode for the movie...

    amp->on();                // Turn on the amp...
    amp->setInput(dvd);       // set it to DVD and...
    amp->setSurroundSound();  // put it into surround sound mode...
    amp->setVolume(11);       // and set the volume to 11...

    dvd->on();                            // Turn on the DVD player...
    dvd->play("Raiders of the lost ark"); // and FINALLY, play the movie!
  }

  void playWithHomeTheaterFacade() {
    // Create all the parts of the home theatre system
    auto amp = std::make_shared<Amplifier>("Yamaha RX-V377 Amplifier");
    auto cd = std::make_shared<CdPlayer>("Marantz A8005 CD Player", amp);
    auto dvd = std::make_shared<DvdPlayer>("My Dvd player", amp);
    auto screen = std::make_shared<Screen>("My Screen");
    auto popper = std::make_shared<PopcornPopper>("My Popcorn Popper");
    auto tuner = std::make_shared<Tuner>("My Tuner", amp);
    auto lights = std::make_shared<TheaterLights>("My Lights");
    auto projector = std::make_shared<Projector>("My Projector");

    popper->on();  // Turn on the popcorn popper...
    popper->pop(); // and start popping...

    lights->dim(10); // Dim the lights to 10%... 

    screen->down();  // Put the screen down...

    projector->on();             // Turn on the projector...
    projector->setInput(dvd);    // set it to DVD...
    projector->wideScreenMode(); // and put it on wide screen mode for the movie...

    amp->on();                // Turn on the amp...
    amp->setInput(dvd);       // set it to DVD and...
    amp->setSurroundSound();  // put it into surround sound mode...
    amp->setVolume(11);       // and set the volume to 11...

    dvd->on();                            // Turn on the DVD player...
    dvd->play("Raiders of the lost ark"); // and FINALLY, play the movie!
  }
}